== Chapter 2 - Message Definitions ==

=== Overview ===

This chapter provides the key definitions of messages that could be supported within the organization's messaging ecosystem. 
It will :

* define the types of messages and some of the guiding principles used to identify and name them. 
* describe the potential fields definitions and formats for each of the message types. 


=== Message Types ===
A message is a general-purpose data structure with no special intent. 
In the integration world, these are typically just streamed between the systems for logging, searching, and for other operational and regulatory reasons.
As a component of the event architecture, there are 3 types of asynchronous messages:

.Events
An *Event* is a message which informs various listeners about something which has happened in the past. 
It is sent by a producer which doesn't know and doesn't care about the consumers of the event. 
There can be multiple consumers of the event, each having their own interest in the event.
This type of messages promotes highly decoupled systems using pub/sub architectures.  

====
[IMPORTANT]
*An Event is an immutable record of a single event at a moment in time.*
====

.Commands
*Commands* trigger some action which should happen in the near future. 
It's typically a one-to-one connection between a producer (who sends the command) and a consumer (who takes and executes the command) and, in a few cases, the order of commands is also of utmost importance. 
Commands are usually performed by actors outside the current system. 
However, commands can also be rejected, requiring new error handling patterns.

The difference in thinking between an event and a command is an event-X has occurred, rather than command-Y which should be executed as part of a conversation or interaction.

====
[IMPORTANT]
*A Command is a request to retrieve some data or perform some action*
====

.Audit
An Audit message is an adhoc publishing of a domain business objects state. 
There is no true triggering action, either from a business process or straight data change. 
It would typically be triggered in batch fashion with a query predicate. 
As part of normal processing, there  will be situations where there are failures in the pipeline, which might lead to data inconsistencies between a systems of record and systems relying on this data. 
In situations where the business objects are very stable and don't change often, the audit message is used to get to eventual data consistency between systems. 
A full business object for a bounded context can be published on a periodic basis and then any consumer caches can be updated. 
Thus, can also be used to seed new consumers with domain data.

<<<
=== Event ===

====
[NOTE]
*Something of interest that has happened in the past*
====

An *Event* represents something that has happened, along the data context at a defined point in time.

.Definitions:
* Result of some outcome
* Collins: a happening or occurrence, esp. when important
// Add Footnote for CloudEvents.io
* CloudEvent Concepts
** An event includes context and data about an occurrence. Each occurrence is uniquely identified by the data of the event.
** Events represent facts and therefore do not include a destination, whereas messages convey intent, transporting data from a source to a given destination.

Event names should indicate a past tense action - a past-participle verb and should be action oriented.
Events are both a historical fact and a notification to other interested parties:

* Notification - a call for action, this is considered a stateless event 
* A state transfer - pushing data wherever it is needed, known as an Event-Carried State Transfer

Events never produce a response object when published.
They could be the result of a business process (i.e.  completed enrollment) or command (i.e. Change medical plan election).
They can't be rejected, but can be ignored. 
There is no expectation of any future action by the publisher.

====
[IMPORTANT]
Events are immutable
====

Applications are like islands. 
Inter application processing is becoming more and more important.
As applications become more specialized, business process will involve multiple services,requiring more integration to provide some specific aspect of the overall process experience.
Although it is not common practice, every application should consider publishing events as part of it's overall design and implementation. 
Today, it is a bit of an afterthought.
Events and Commands should be first class elements of the application.
Even if there is no requirement for this in the present for an application, it will be at some point in the future. 
Every quality application domain engine should provide API for request-reply processing and publish events for any downstream application.
A good event design will anticipate what events might be of interest and publish them.

<<<

=== Command ===

====
[NOTE]
*Represents a request to perform an important action task or retrieve data*
====

.Definitions
* Webster Definition: _to direct authoritatively_
* Represents an intent to perform some sort of action

The requested action of the command has not yet happened
(e.g. Change medical plan election). As opposed to events, where some action has already occurred.
The commands should be named with an imperative verb.
It has an explicit expectation that something (a state change or side effect) will happen in the future.
Commands can be rejected, but it these cases it is important for any consumer to response with some form of message.
Typically, this is part of a Ux conversation or program-to-program interaction. 
However, there can one-way requests or fire-forgot messages with no response.

Commands can be used in situations where an async request/reply is desired.
However, this is not to be confused with a synchronous Request/reply like REST API.
The message can provide a call back information, which can be used in an asynchronous conversation with another consumer.


<<<
=== Audit ===

Represents the current state of a business object - Published on specific schedule 

====
[NOTE]
Audit messages can be used to synchronous data between systems of records and any consumer who is dependent on that data
====

More details to come.
