// Cloud Event Project Notes
// A specification for describing event data in a common way 
//
// Why Cloud Events?
// 
// //Events are everywhere, yet event publishers tend to describe events differently.
//
// Value Proposition
// 
// This section describes some of the use-cases that explain the value of CloudEvents.
// 
// Normalizing Events Across Services & Platforms
// Facilitating Integrations Across Services & Platforms
// Increasing Portability of Functions-as-a-Service
// Improving Development & Testing of Event-Driven/Serverless Architectures
// Event Data Evolution
// Normalizing Webhooks
// Policy Enforcement
// Event Tracing
// IoT
// Event Correlation

== Chapter 1 ==

[lead,indent=5]
 Events are everywhere, yet event publishers tend to describe events differently 
   - CloudEvents.io Project <<cloudEvents>>

=== Why is Event Driven Architecture critical to tomorrow's applications? ===

Today, the primary interaction model for web based architectures to communicate to other systems is REST API via HTTP.
This interaction paradigm  is called *Synchronous Request-Reply*, where the client is _waiting_ for a response from the service.
This is driving the overall user experience, where the user presses a button or link and then waits for a response. 
As more mobile applications are calling multiple backend services in a single request, this is causing longer wait times for the user as it takes time for all the requests to respond.
Ux Designers feel strongly that an synchronous response is the best user interaction model.

However, there are many application interaction models in practice today that do not fit this model. 
People may not think of it in this way, but email and text are really disconnected (asynchronous) interaction models. 
The person submits a communication message and then can perform other actions, while they wait for a notification that a response is available for review (e.g. waiting for an email response).
If the asynchronous request is fast enough, the user does not know the difference. 
So there is precedence for user interface design using an asynchronous model. 


So, why are interface designers not using a disconnected paradigm like email or text? 
These types of interactions are very hard to design for. 
There are some situations, where the user expects an immediate response. 
It is hard in an asynchronous event driven model to simulate a synchronous response to the user.
It requires a very low latency interaction approach, which was hard to do with older technologies. 
It was just easier to design a synchronous model when all the interactions were within the company computing ecosystem and there wasn't available technologies other than HTTP to provide an appropriate user response.

_Event Driven Architectures are key to providing a rich satisfying user experience as applications become more complicated and more and mores services are being provided by outside providers_ 

A synchronous model also has a major impact on the computing resources required to support the application.
Instead of having to provision servers for maximum requests, that may sit idle, one can have fewer workers in the background continuously managing the work. An event driven architecture following an asynchronous approach is always a more efficient use of computing resources than a asynchronous approach.

_Event Driven Architectures are key to a more efficient use of computer resources.
This is even more important is a cloud based environment where the pricing is based on actual detail usage._

Asynchronous technologies have been around for a very log time. 
The IBM mainframe environment had MQ middleware that allowed inter-machine communication and intra-platform integration (primarily distributed platform). 
There are even more modern technologies, like Kafka and RabbitMQ. 
In prior application designs and even today, these technologies were used for inter-platform communication and more balanced resource allocation and management. 
There were mostly used for underlying application interaction, but not used in an interface design. 

====
[IMPORTANT]
_The key to designing these type of applications is establishment of a set of event design standards and governance processes within the organization, along using asynchronous messaging technologies (IBM MQ, Kafka, RabbitMQ)_ +
The purpose of this document is to provide a set of event specifications that can work at the scale of a large organization.
====

_What is different in today's environment?_

* Sophisticated application are leveraging more domain services that are being provided by parties who are outside of the control of the organization and the central application. 
This leads to more interactions and increases user experience wait time as the services are executed in a sequential manner.

* There are more modern messaging technologies are available to application architects to lower time time latency. 
There is also more practical real life experience in Event Driven Architecture for architects and designers to leverage

* User are becoming more comfortable with a disconnected interaction model, where they submit a request, work on a different task and then act on the response they get after the fact. Techniques, like deep linking from the response, to the specific page within the application are becoming more prevalent. 

* Real time analytics being processed by AI and Machine Learning are becoming value tools for decision making within an organization. Events are an important technique in making it successful.

_As with any other scaled integration strategy, the key to success is standards and event design needs to follow this strategy._

=== Why are event design standards critical for organizational success? ===

As an organization's application portfolio continues to grow, so does it's integration requirements between these application.
In some cases, it is very difficult to create tightly integrated solutions.
In addition, users are expecting their outcomes to move faster and having their entire process completed in a single session. 
Multiple applications are interested in the same events leading to increased complexity when using point to point approaches. Publish-subscribe approaches with events helps reduce this complexity.
Requirements for more integrations, faster deployment, reduced complexity and low latency integration is leading to more and more use of events and event driven architecture.

The design of *events* can come in all shapes and sizes. 
They can be as low level as a single data element changing(changing one's email address), to an entire business process completing (completing a transfer in a bank account).
With the move to more domain oriented organizational structures, independent autonomous groups will be designing events.
This will cause a prolific number of events being created by an organization. 
Without organizational design standards and guidelines, the lack of consistency will lead to chaos losing all the benefits of an Event Driven Architecture.

Event design standards are critical to the success of an Event Driven Architecture as the strategy is scaled up within the organization.
It isn't enough to commit to using events as a key integration strategy, the organization needs standards and governance in the design of events. 
To support friction-less and over-reaching governance, the organization needs comprehensive design guidelines to support the event designers and give rubrics to the governance groups on how to judge the quality of the design.

// Discuss interoperability as a key reason for standards

