== Chapter 8 Audit Message Specifications ==

=== Overview ===
Key features of Audit Message Specification are:


=== Audit Types ===
The follow sections provide the specification for the types of Audits support by the architecture. (Note: Some Audit types are in the prototype stage)  +
The Audit types are:

=== Audit Message Overview ===

The standard audit message is a JSON document containing one JSON object named *message*. 
The *message* object contains 3 child JSON objects: 

* Common Message Header - Common across all messages, independent of Audit type and audit
* Audit Type Header - Common header for specific Audit types 
* Audit Message Body - Free form body for each Audit defined with the Audit type


=== Internal Audit JSON Structure ===
To keep it simple and easy to produce and consume, the audit message has a very flexible structure and is basically an unstructured document. 
The goal is to have a schema for the header, each audit type header and every audit data (i.e body) itself. 
We would like to have a schema dictionary which has a JSON or AVRO schema as it values and it's keyed by some name. The hierarchy is as follows:

* There is only one header schema (key name: header)
* To determine the <auditTypeheader> name, the header.messageNamespace field contains the name of the audit type
* To determine the body schema name, the header.auditBodyNamespace field determine the name for the body schema

[NOTE]
====
The internal audit structure looks as follows:

{"message" : +
	"header" : {   ...  }, +
	"_auditTypeHeader_" : { ... }, +
	"body"  : { ... }
}

====