== Chapter 4  - Domain Event Examples - Consumer Business Events ==

Each domain or industry has its events within an event category.
To help get a better understanding of the general specification, this chapter provides some real-life examples. These examples are taken from the author's experience in developing HR/Benefits Administration systems. 
These examples should also apply to any consumer-based application. 
The following real-life consumer-related events are discussed:

* Business Process State Changes
* Business Domain Object Data Changes
* Consumer User Experience (Ux) Application Interactions 
* Consumer General Activities 

In addition to the above categories, some events are very generic or general. These Undefined events are a free-form category suitable for events that are entirely custom to the producer.

All of these event categories would use the Common Message Header described in the prior chapter.

=== Business Process State Change Event ===

The purpose of this event category is to capture events related to the state changes in the processing of a business process.
These events are sometimes known as workflows or business transactions and are used to manage the changes to business domain objects. 
These processes will contain many tasks or steps to help arrive at the process's outcome.
Typically, upon the completion of a business process, the process will update a business object. 
This might also create a Business Object Data Change event.

Events can be generated from two types of business processes. 

1) A _long-running state machine-based_ process that has many wait states, with time gaps in between the actions of the business process. 

2) A _straight-through_ process, where there are no waits in the process and the actions are completed in a single unit of work. Typically, it is all or nothing from a commit standpoint.

Business Process examples:

* New Hire Onboarding
* 401k Contribution Rate Change
* Annual Benefits Enrollment
* Defined Benefit Retirement

Examples of state changes include:

* Started
* Completed
* Validated
* In Error

==== Business Process State Change Event Category Header Specifications ====

====
[IMPORTANT]
*JSON Name for _Event Category Header_: bpEventHeader*
====

.Header Attributes

.Schema Fields Table
[width= 80%, options=header]
|================================
| Field Name | Attributes
| businessProcessReferenceId | String; Required
| businessProcessTemplateId | String; Required
| businessProcessDescription | String; Optional
| businessProcessStatus | String; Required
| businessProcessEffectiveDate | Date; Required
| businessProcessChangeTimestamp | Timestamp; Required
|================================

.Schema Field Definitions
[horizontal]
businessProcessReferenceId:: Describes the primary key or Business Process Reference Identifier of the business process instance as described in workflow management platform(s). 

businessProcessTemplateId:: Describes the internal identifier of the business process definition. 
This is a template that is used to create the actual specific instances of the business process. 

businessProcessDescription:: Describes the long more formal description of the business process. 

businessProcessStatus:: Business Process status. +
Sample Values:
* Created
* Validated
* Invalid
* Completed
* Canceled

businessProcessEffectiveDate:: Effective date of the business process

businessProcessChangeTimestamp:: Timestamp of when the business process was changed. 
The timestamp must be in the ISO 8601 date format standard.

.EventName Standards
For the eventName, the standard will be the following fields separated by a colon (":") in camel case.

* _tag_ which represents the business process name
* _action_ which represents the business process action
 
.Tag Definition
The tag represents the business process name. 

Format:

* Free format single alpha or numeric value
* No formal specification is defined

.Action Definition
The action represents the types of actions that result from the change in the state of the business process during the processing of the consumer's business process.

Action Component Sample Values:

 * Started
 * Updated
 * Completed
 * Canceled

.Body Definition Considerations
The eventData section is named *eventData*. 
The *eventData* can be any valid JSON schema.
It should contain key information about what action or event triggered the change in the state of the process. 
In some cases, a Command will be the triggering event that created this change.

<<<

=== Business Object Data Change Event  ===

The purpose of this event category is to capture the changes to key domain business objects.
The event can have both the before and after image or a list of data elements changes, along with the new and old values.

Sample Business Objects include:

* Person
* Employee
* Person 401k Benefits
* Person Medical Benefits
* Person Document

Data actions include:

 * Creation
 * Updated
 * Deletion
 * Master Data Management Document Merge/Split

==== Business Objects Data Change Event Category Header Specifications ====

====
[IMPORTANT]
*JSON Name for _Event Category Header_: boEventHeader*
====

.Header Attributes

.Schema Fields Table
[width= 80%, options=header]
|================================
| Field Name | Attributes
| businessObjectResourceType | String; Required
| businessObjectIdentifier | String; Required
| additionalBusinessObjectResource | Array; Optional
| - additionalBusinessObjectResourceType | String; Optional
| - additionalBusinessObjectResourceId | Date; Optional
| dataChangeTimestamp | Timestamp; Required
|================================

.Schema Field Definitions
[horizontal]
businessObjectResourceType:: Describes the primary domain data object type that was changed. +
Sample Values:

* person
* personDefinedContribution
* personHealthManagement
* personDefinedBenefit
* personDefinedBenefitCalculation
* personDocument
//Editor: Think about moving this to 'tag'. Need to determine in the Identifier is included in the tag

businessObjectIdentifier:: Provides the primary key of the business object that was changed.
This information might be a duplicate of what is in the Common Message Header.

additionalBusinessObjectResource:: Provides any additional resource type and key to help further identify the component that changed. 
This is similar to the path (../resource/{id} ) in a REST URL

additionalBusinessObjectResourceType:::: Additional resource type

additionalBusinessObjectResourceId:::: Additional resource identifier or primary key

dataChangeTimestamp:: Timestamp of the data change in the source platform. 
The timestamp must be in the RFC 3339/ISO 8601 date format standard. 
See Appendix for details.

.EventName Standards
For the eventName, the standard will be the following fields separated by a colon (":") in camel case.

* _tag_ which represents the business object name and 
* _action_ which represents the CRUD operation taken against the business object

.Tag Definition
The tag represents the business object name. 
//Editor Note: Should tag replace 'businessObjectResourceType'.

Format:

* Free format single alphanumeric value
* No formal specification is defined

.Action Definition
The action defines the type of data maintenance (CRUD) action taken on the business object.
//Editor Note: action is replacing the dataAction field in prior versions.

* Action Component Sample Values

dataAction:: Describes the data change or CRUD action performed on the business object.- Create, Update, Delete. 
Also includes any primary key changes and Master Data Management (MDM) document merging. 
** Create
** Update
** Delete
** MdmDocumentMerge
** MdmDocumentSplit


.Body Definition Considerations

* The eventData section is named *eventData*
** *eventData* can be any valid JSON schema
* Contains one predefined element *extension*
** Extension is a private area that can contain its schema
** The field is a map/array with:
*** Namespace as a key and,
 *** Any valid JSON schema as its value

.Data Fields Best Practices by Data Action

[horizontal]
Update::

The recommendation for what data fields to document is to provide only those fields that changed during the update, providing both old and new values. + 
+
Best practice recommendations:

* For Personal Identification Information (PII) fields:
** Fields: Bank/Credit Account Numbers, 
** Provide old/new unchanged from CustomerMaster; no masking required
* For Arrays:
** Provide Lowest Level Detail field, including all cascading keys  
** Example: Contact -> streetAddress -> { AddrID ->  OldZipcode, newZipcode  }
** Include all the fields at the same level as the changed field in the entire array data object 
** For fields in a high level/hierarchy, including all keys and simple primitive types (strings, numbers, etc ) at the same hierarchy  
*  Do not include objects or arrays  in the higher levels 
* Do not include non-changing arrays at the same level

Create::
Provide the entire New entity. 
The alternative is to only provide foreign keys, which can be used to retrieve data from an API or database. 

Delete:: 
Only provide a delete event if the entire document is being deleted, not if one of the source systems deleted a person.
In the eventData, provide the primary key.

=== User Experience Action Event ===

The Ux Action events are intended to capture the actual keyboard/mouse events performed by the user
 - displaying pages, clicking buttons or links, entering text. 
These are events related to the behavioral actions taken by the user in online or digital channels. 
Channels include web, mobile, IVA/chat, and other future user devices like Voice Assistants.
These events are not the result of any business process or data change events. 

All Ux applications generate log records to help debug and provide data for analytics.  
These UX logs are events and should be treated as such.
There is no need to have both a log record and events. 
Events can handle both needs.

Ux Action Events are used for: 

* Publishing behavior actions (clicks) for data reporting and analytics
* Provide notifications to non-domain processes (document management, campaigns) to drive their underlying processes

Actions may include, but are not limited to:

* Button clicks
* Link or action selections
* Page or screen displays
* Hover
* IVA or chat intents

The intention is to capture the actual true or syntactic Ux actions along with a navigation/breadcrumb label. 
The goal is not to add any business semantics to these events. 
This allows the UX developer to focus on the UX component and action, not trying to connect it to the business semantics.
There should be enough context in the label for another offline process (e.g. analytics process) to create another event with the business semantics of the user's action. 

In most systems, these are considered logging or debugging actions.
By adding a session identifier as a correlation value and adding additional related business object information to the event, it makes it easier for analytics processes to tie a user's session together to identify key trends.

==== User Experience Action Event Category Header Specifications ====

====
[IMPORTANT]
*JSON Name for _Event Category Header_: uxEventHeader*
====
Header Attributes

.Schema Fields Table
[width= 80%, options=header]
|================================
| Field Name | Attributes
| channel | String; Required
| userDevice | String; Required
| deviceTimestamp | Array; Optional
| sessionId | String; Optional
| sessionStartTimestamp | Timestamp; Optional
| applicationVersion | String; Optional
|================================

.Schema Field Definitions

[horizontal]
channel:: Describes the channel (or UI application) where the event is generated.

userDevice:: Identifies the device used by the end-user.

deviceTimestamp:: Represents the time stamp on the device (May be different from the publisher timestamp). 
The timestamp must be in the RFC 3339/ISO 8601 date format standard. 
See Appendix for details.

sessionId:: Represents the unique session of the end-user on the channel.

sessionStartTimestamp:: Session creation or start time. 
The timestamp must be in the RFC 3339/ISO 8601 date format standard. +
See Appendix for details.

applicationName:: User Experience application name 

applicationVersion:: Version of the application

.EventName Standards
For the eventName, the standard will be the following fields separated by a colon (":") in camel case.

* UxControlName
* UserAction

.Tag Definition
In the Ux channels, there is an unbounded set of device actions a user can take: pressing buttons, displaying pages, and starting process flow. 
In addition, there is an unbounded set of specific widgets/controls (buttons, etc.) throughout the interface. 
For reporting and other activities, there is a need to capture that a specific control has been acted upon -  pressing a specific button within a specific group of controls within a page within a business conversation flow. 

To reduce the complexity in trying to capture all the levels and types of components, the recommendation is to encode all hierarchical information (i.e. breadcrumbs) into a single label or tag using a structured format.
This tag along with the user action on this tag should reduce the complexity of the event structure and make it easier for the consuming tools to do their work.
This will also make it easier for the UX developer since they will not be dealing with the business aspect of the action.
They only need to produce an event (a.k.a. log) with a label and the actual mouse/keyboard action.
The interpretation of the label/action will be an outside downstream activity.

To make it more human-readable, there will be an encoding standard to make it more human-readable and make it easier to parse the tag if necessary. The tag values need to take into account all types of user interfaces and devices. 
There is a need to support new and emerging interfaces beyond web and mobile channels. The following sections discuss the naming approach.

.Tag Component Valid Values

[horizontal]

Web Channel::
* Flow or Conversation - A user's perceived outcome process or unit of work; Denotes flow of interaction (pages) or conversation between user and system
** Page 
** Widget or Multiple Control Component
* Elemental Ux Control
** Button, includes clickable icons - Clickable
** Link - Clickable
** CheckBox - Selectable
** Text - Display, Hover, Table Element
** TextBox - Keyboard Actions -> Tabbing ,Enter pressed
** Bounded Lists -> Radio Buttons or checkboxes or DropDown Lists or Dials - Selectable

Mobile:: TBD

Smart Assistant/AlexaIVA/Chat:: TBD

Other on Non-Channel:: Treatment or Theme  Example xxxA/xxxB 

.Format
* Ordered sets of tuples separated by underscore '_'
* The tuple is the following fields separated by dash '-'
** LogicalName determined by Ux Designer and Data Analyst 
** UxControl Valid Value in all caps
* The order is from the highest level (aFlow) to specific UX Control, (Button)

Format: <Flow_Name>-FLOW_<Page_Name>-PAGE_<ButtonLabel>-BUTTON +
Example: Retirement-FLOW_LandingPage-PAGE_ok-BUTTON (which means the user accepted their retirement elections and they will be processed)

.Action Definition
The action defines the actual keyboard/mouse actions taken by the user when interacting with the channel/device. +
Sample Values for userAction:

* Displayed
* Clicked
* Entered

.Body Definition Considerations
* The eventData section is named *eventData*
** *eventData* can be any valid JSON schema
* Contains one predefined element *extension*
** Extension is a private area that can contain its schema
** The field is a map/array with:
*** Namespace as a key and,
*** Any valid JSON schema as its value
* This can be any significant data or data of interest for reporting at the time of the UX Event

<<<

=== Consumer Goal Event ===

These are events related to the action taken by the consumer in the context of reaching a personal goal. 

A goal is a non-transactional outcome the consumer is trying to attain. +
For example, the person wants to lose 20lbs as a health goal

Actions may include:

* Started
* Completed

==== Consumer Goal Event Category Header Specification ====

====
[IMPORTANT]
The Personal goal only requires the main header +
*JSON Name for _Event Category Header_: pgEventHeader*
====

.Tag Definition
The tag represents the name of the personal goal in a machine-readable format.

Format:

* Free format single alphanumeric value
* No formal specification is defined

.Action Definition
The action defines the type of task actions taken against a personal goal.

Action Component Sample Values :

* Started
* Completed

.Body Definition Considerations
* The eventData section is named *eventData*
** eventData  can be any valid JSON schema
* Contains one predefined element *extension*
** Extension is a private area that can contain its schema
** The field is a map/array with:
** Namespace as a key and,
** Any valid JSON schema as its value
** This can be any significant data or data of interest for reporting at the time of the UX Event