== Chapter 4  - Domain Event Examples - Consumer Business Events ==

Each domain or industry has their own event types.
To help get a better understanding of the general specification, this chapter provides some real life examples. These examples are taken from the author's experience in developing HR/Benefits Administration system. 
These examples should also apply to any consumer based application. 
The following real life consumer related events are discussed:

* Business Process State Changes
* Business Domain Object Data changes
* Consumer User Experience (Ux) Application Interactions 
* Consumer General Activities 

All of these event would use the Common Message HeaderHeader described in the prior chapter.

=== Business Process State Change Event ===

The purpose of this event type is to capture events related to the processing of a business process.
These events are sometimes known as workflows or business transactions and are used to manage the changes to business domain objects. 
Typically, upon the completion of a business process, the process will update a business object. 
This might also create a Business Object Data Change event.

Events can be generated from two types of business processes. 

1) A _long running state machine based_ process that has many wait states,with time gaps in between the actions of the business process. 

2) A _straight through_ process or single task process, where there are no waits in the process and the action is completed in a single unit of work. Typically, it is all or nothing from a commit standpoint.

Business Process examples:

* Contribution Rate Change
* Annual Benefits Enrollment
* Defined Benefit Retirement

State changes includes:

* Started
* Completed
* Validated
* In Error

==== Business Process State Change Event Type Header Specifications ====

====
[IMPORTANT]
*JSON Name for _Event Type Header_: bpEventHeader*
====

.Header Attributes

.Schema Fields Table
[width= 80%, options=header]
|================================
| Field Name | Attributes
| businessProcessReferenceId | String; Required
| businessProcessId | String; Required
| businessProcessDescription | String; Required
| businessProcessStatus | String; Required
| businessProcessEffectiveDate | Date; Required
| businessProcessChangeTimestamp | Timestamp; Required
|================================

.Schema Field Definitions
[horizontal]
businessProcessReferenceId:: Describes the primary key or Business Process Reference Identifier of the business process  instance as described in platform(s). 

businessProcessId:: Describes the internal identifier of the business process definition. It is a template that is used to create the actual specific instances of the business process. 

businessProcessDescription:: Describes the long more formal description of the business process. 

businessProcessStatus:: Business Process status. +
Sample Values:
* Created
* Validated
* Invalid
* Completed
* Canceled

businessProcessEffectiveDate:: Effective date of the business process

businessProcessChangeTimestamp:: Timestamp of when the business process was changed. 
The timestamp must be in the ISO 8601 date format standard.

.EventName Standards
For the eventName, the standard will be the following fields separated by a colon (":") in camel case.

* _tag_ which represents the business process name
* _action_ which represents the business process action
 
.Tag Definition
The tag represents the business process name. 

Format:

* Free format single alpha or numeric value
* No formal specification is defined

.Action Definition
The action represents the types of actions that result from the change in state of the business process during the processing of the consumer's business process.

Action Component Sample Values:

 * Started
 * Updated
 * Completed
 * Canceled

.Body Definition Considerations
The body section is named *body*. 
The *body* can be any valid JSON schema.
It should contain key information about what action or event triggered the change in state of the process. 
In some case, a Command with be the triggering event at create this change.

<<<

=== Business Object Data Change Event  ===

The purpose of this event type is to capture the changes to key domain business objects.
The event can have both the before and after image or a list of data elements changes, along with the new and old values.

Sample Business Objects include:

* Person
* Employee
* Person 401k Benefits
* Person Medical Benefits
* Person Document

Data actions include:

 * Creation
 * Updated
 * Deletion
 * Master Data Management Document Merge/Split

==== Business Objects Data Change Event Type Header Specifications ====

====
[IMPORTANT]
*JSON Name for _Event Type Header_: boEventHeader*
====

.Header Attributes

.Schema Fields Table
[width= 80%, options=header]
|================================
| Field Name | Attributes
| businessObjectResourceType | String; Required
| businessObjectIdentifier | String; Required
| additionalBusinessObjectResource | Array; Optional
| - additionalBusinessObjectResourceType | String; Optional
| - additionalBusinessObjectResourceId | Date; Optional
| dataChangeTimestamp | Timestamp; Required
|================================

.Schema Field Definitions
[horizontal]
businessObjectResourceType:: Describes the primary domain data object type that was changed. +
Sample Values:

* person
* personDefinedContribution
* personHealthManagement
* personDefinedBenefit
* personDefinedBenefitCalculation
* personDocument
//Editor:Think about moving this to 'tag'. Need to determine in the Identifier is included in the tag

businessObjectIdentifier:: Provides the primary key of the business object that was changed.
This information might be a duplicate of what is in the Common Message Header.

additionalBusinessObjectResource:: Provides any additional resource type and key to help further identify the component that changed. 
This is similar to the path (../resource/{id} ) in a REST URL

additionalBusinessObjectResourceType:::: Additional resource type

additionalBusinessObjectResourceId:::: Additional resource identifier or primary key

dataChangeTimestamp:: Timestamp of the data change in the source platform. 
The timestamp must be in the RFC 3339/ISO 8601 date format standard. 
See Appendix for details.

.EventName Standards
For the eventName, the standard will be the following fields separated by a colon (":") in camel case.

* _tag_ which represents the business object name and 
* _action_ which represents the CRUD operation taken against the business object

.Tag Definition
The tag represents the business object name. 
//Editor Note: Should tag replace 'businessObjectResourceType' .

Format:

* Free format single alpha numeric value
* No formal specification is defined

.Action Definition
The action defines the type of data maintenance (CRUD) action taken on the business object.
//Editor Note: action is replacing the dataAction field in prior versions.

* Action Component Sample Values

dataAction :: Describes the data change or CRUD action performed on business object.- Create, Update, Delete. 
Also includes an primary key changes and Master Data Management (MDM) document merging. 

* Create
* Update
* Delete
* MdmDocumentMerge
* MdmDocumentSplit


.Body Definition Considerations

* The body section is named *body*
** *body* can be any valid JSON schema
* Contains one predefined element *extension*
** Extension is a private area that can contain its own schema
** The field is an map/array with:
*** Namespace as a key and,
 *** Any valid JSON schema as its value

.Data Fields Best Practices by Data Action

[horizontal]
Update::

The recommendation for data fields to report is to provide only the fields that changed providing both old and new values. +
Best practice recommendations:

* Personal Identification Information (PII)
** Fields: Bank/Credit Account Numbers, 
** Provide old/new unchanged from CustomerMaster; no masking required
* Arrays
** Provide Lowest Level Detail field, include all cascading keys  
** Example: Contact -> streetAddress -> { AddrID ->  OldZipcode, newZipcode  }
** Include all the fields at the same level as the changed field in entire array data object 
** For fields in a high level/hierarchy, include all keys and simple primitive types (strings, numbers,etc ) at the same hierarchy  
*  Do not include objects or arrays  in the higher levels  Do not include non-changing arrays at the same level

Create::
Provide the entire New entity. 
The alternate is too only provide foreign keys, which can be used to retrieve data from an API or data base. 

Delete:: 
Only provide a delete event if the entire document is being deleted, not if one of the source systems deleted a person.
In the body, provide the primary document key  (UniversalId or  Mongo _id ) and any IdMapping table
If the object/person is being delete in a given platform, but the person still exists in another platform, treat as an Update.
Only delete when no more IdMappings exist in the document

.Master Data Management Platforms/CustomerMaster

_Editor: Should this be removed_
[horizontal]
Merge::
** Treat as an MDM Merge Update event with two sections of data, one for survivor and one for deleted  
** Both sections
** Survivor _id & Deleted _id
** Id Mapping for both survivor and deleted
** Survivor document section contains the update record for the survivor document (see Update section)
** Deleted document section 
** Reason for merge
** The Platform that caused the change to occur
*** System Instance
*** Merge Field Change (old, new)

Split:: No new events, just two new event being generated
Web service call to deletePersonId service, which cleans up IdMapping and domain sections.
Generates a Normal Update event.
Web Service call refreshPersonForInternalId service, which causes a refresh through .

Ingest:: Generates a Normal Update event 

<<<

=== User Experience Action Event ===

_Ed: Ad some content around: In Ux Events, state that UX logs are really events and should be treated as them. In particulat trying ot log business action. It also works for debugging and tracing log entries._

The Ux Action events are intended to capture the actual keyboard/mouse events performed by the user
 - displaying pages, clicking button or links, entering text. 
These are events related to the behavioral actions taken by the user in the online channels. 
Channel include web, mobile, IVA/chat and other future user devices like Voice Assistants.
These events are not the result of any business process or data change events. 

They are used for: 

* Behavior actions for data reporting and analytics
* Provide notifications to non-domain processes (document management, campaigns) to drive their underlying processes

Actions may include, but not limited to:

* Button clicks
* Link or action selections
* Page or screen displays
* Hover
* IVA or chat intents

The intention is to capture the actual true or syntactic actions along with a navigation/breadcrumb label. 
The goal is not to add any business semantics to the event. 
There should be enough context in the label for another offline process (e.g. analytics process) to create another event with the business semantics of the users action. 

In most systems, these are considered logging or debugging actions.
By adding a session context as a correlation value and adding additional related business object information to the event, it makes it easier for analytics processes to tie a users session together to identify key trends.

==== User Experience Action Event Type Header Specifications ====

====
[IMPORTANT]
*JSON Name for _Event Type Header_: uxEventHeader*
====
Header Attributes

.Schema Fields Table
[width= 80%, options=header]
|================================
| Field Name | Attributes
| channel | String; Required
| userDevice | String; Required
| deviceTimestamp | Array; Optional
| sessionId | String; Optional
| sessionStartTimestamp | Timestamp; Optional
| applicationVersion | String; Optional
|================================

.Schema Field Definitions

[horizontal]
channel:: Describes the channel (or UI application) where the event generated.

userDevice:: Identifies the device used by end-user.

deviceTimestamp:: Represents the timestamp on the device (May be different from the publisher timestamp). 
The timestamp must be in the RFC 3339/ISO 8601 date format standard. 
See Appendix for details.

sessionId:: Represents the unique session of end user on our channels.

sessionStartTimestamp:: Session creation or start time. 
The timestamp must be in the RFC 3339/ISO 8601 date format standard. +
See Appendix for details.

applicationName:: User Experience application name 

applicationVersion:: Version of the application

.EventName Standards
For the eventName, the standard will be the following fields separated by a colon (":") in camel case.

* UxControlName
* UserAction

.Tag Definition
In the Ux channels, there are an unbounded set of device actions a user can take: pressing buttons, displaying pages, starting process flows. 
In addition, they are an unbounded set of specific controls (buttons, etc) throughout the interface. 
For reporting and other activities, there is a need to capture that a specific control has been acted upon: pressing a specific button within a specific group of controls within a page within a business process flow. 

To reduce the complexity in trying to capture all the levels and types of components, the recommendation is to  are encode all hierarchical information (i.e. breadcrumbs) into a single label or tag using a structured format.
This tag along with the user action on this tag should reduce the complexity of the event structure and make it easier for the consuming tools to do their work.
This will also make it easier for the UX developer since they will not be dealing with the business aspect of the action.
They only need to produce an event (a.k.a. log) with a label and the actual mouse/keyboard action.
The interpretation of the label/action will be a outside downstream activity.

To make it more human readable, there will be an encoding standard to make it more human readable and make it easier to parse the tag if necessary. The tag values need to take into account all types of user interfaces and devices. 
There is a need to support new and emerging interfaces beyond web and mobile channels. The following sections discuss the naming approach.

.Tag Component Valid Values

[horizontal]

Web Channel::
* Flow - A user's perceived outcome process or unit of work; Denotes flow of interaction (pages) or conversation between user and system
** Page 
** Widget or Multiple Control Component
* Elemental Ux Control
** Button, includes clickable icons - Clickable
** Link - Clickable
** CheckBox - Selectable
** Text - Display, Hover, Table Element
** TextBox - Keyboard Actions -> Tabbing ,Enter pressed
** Bounded Lists -> Radio Buttons or checkboxes or DropDown Lists or Dials - Selectable

Mobile:: TBD

Smart Assistant/AlexaIVA/Chat:: TBD

Other on Non-Channel:: Treatment or Theme  Example xxxA/xxxB 

.Format
* Ordered sets of tuples separated by underscore '_'
* The tuple is the following fields separated by dash '-'
** LogicalName determined by Ux Designer and Data Analyst 
** UxControl Valid Value in all caps
* The order is from highest level (aFlow) to specific UX Control, (Button)

Format: <Flow_Name>-FLOW_<Page_Name>-PAGE_<ButtonLabel>-BUTTON +
Example: Retirement-FLOW_LandingPage-PAGE_OK-BUTTON (which means the user accepted their retirement elections and they will be processed)

.Action Definition
The action defines the actual keyboard/mouse actions taken by the user when interacting with the channel/device. +
Sample Values for userAction:

* Displayed
* Clicked
* Entered

.Body Definition Considerations
* The body section is named *body*
** *body* can be any valid JSON schema
* Contains one predefined element *extension*
** Extension is a private area that can contain its own schema
** The field is an map/array with:
*** Namespace as a key and,
*** Any valid JSON schema as its value
* This can be any significant data or data of interest for reporting at the time of the UX Event

<<<

=== Consumer Goal Event ===

These are events related to the action taken by the consumer in the context of reaching a personal goal. 

A goal is non-transactional outcome the consumer is trying to attain. +
For example, the person wants to lose 20lbs as a health goal

Actions may include:
* Started
* Completed

==== Consumer Goal Event Type Header Specification ====

====
[IMPORTANT]
The Personal goal only requires the main header +
*JSON Name for _Event Type Header_: pgEventHeader*
====

.Tag Definition
The tag represents the name of the personal goal in a machine readable format.

Format:
* Free format single alpha numeric value
* No formal specification is defined

.Action Definition
The action defines the type of task actions taken against a personal goal.

Action Component Sample Values :
* Started
* Completed

.Body Definition Considerations
* The body section is named *body*
** body  can be any valid JSON schema
* Contains one predefined element *extension*
** Extension is a private area that can contain its own schema
** The field is an map/array with:
** Namespace as a key and,
** Any valid JSON schema as its value
** This can be any significant data or data of interest for reporting at the time of the UX Event