== Chapter 5 - System Event Example - Runtime Operations Events ==

Runtime Operation Events are "occurrences" that happen during the running of an application on a specific platform or system resource (server, database, broker, etc.). 
For system resources, they are focused mostly on the management of the resource. 
For application programs, the events are related to debugging and application logic tracing.

=== Platform Processing Event  ===
These events are related to the action of completing a discreet process or unit of work and providing the resource computation of that unit of work. 

These events reflect the fact that: 

* The application process occurred, which is used for counting instances of the process, 

* the time stamps of when it occurred, which are used for elapsed time and windows of time calculations, 

* The timestamp of the additional resource usage, which is used for more detailed resource consumption analytics, and 

* any additional status and metadata related to the process of the unit of work. 

The event can be used for both operational and application events where counting and resource utilization reporting are of interest to the business.

Platform processing units of work being metered include:  

* API Gateways and Docker Containers  -> Service API calls
* Enterprise CI/CD Build pipeline -> API Service builds and deployments

=== System Resource Manager Event ===

*Under consideration*

These events are related to the actions of managing a system resource manager.  This includes the overall operations of the resource manager and the system administrator's actions to administer the resource manager.

Examples of a resource manager: 
* Server(Hardware with OS), 
* JVM
* Web Server 
* Docker container 
* Database manager 
* Queue manager/message broker

A resource manager has the following characteristics: 

* The platform contains important application data  
* The resource is shared by multiple applications
* The resource is managed centrally by a system operations staff, who is responsible for the installation, upgrade, and overall operations of the resource
* Privileged access authority is required to perform system administration functions

Resource manager operational event actions include:  

* Started
* Stopped
* Aborted
* Restarted

System Administrator event actions include:

* Logon
* Password changed
* Commands (?)
* Group Functions (?)

=== Potential Future Operational Events ===
* Runtime System Error Events - Runtime Events because of hardware or software issues
* Code Deployment Events - DevOps Events because of program/business logic development. Include both code and configuration
* Client Deployment Events - Events related to the deployment of client assets, in particular provision migrations.
Might also include client-level processing runtime errors

=== Operations Platform Process Event ===

==== Platform Process Event Header

====
[NOTE]
JSON Name: oppEventHeader
====
.Header Attributes

.Schema Fields Table
[width= 80%, options=header]
|================================
| Field Name | Attributes
| platformProcessStartTimestamp | Timestamp; Required
| platformProcessEndTimestamp | Timestamp; Required
| platformProcessElapsedTime | Float; Optional
| platformProcessEffectiveDate | Date; Optional
| platformProcessStatus | String; Optional
|================================

.Schema Field Definitions
[horizontal]
platformProcessStartTimestamp:: Timestamp of when the resource consumption started. The timestamp must be in the RFC 3339/ISO 8601 date format standard. See Appendix for details.
platformProcessEndTimestamp:: Timestamp of when the resource consumption ended. The timestamp must be in the RFC 3339/ISO 8601 date format standard. See Appendix for details.
platformProcessElapsedTime:: Elapse time in milliseconds
platformProcessEffectiveDate:: Effective Date of process
platformProcessStatus:: Process status. +
Sample Values:
* Aborted
* Completed
* Canceled

.Potential Platform Process Header Fields
* API/Program call Request and Response size
* Memory size at event publication
** Heap sizes, etc
* CPU utilization for process
* Thread count at event publication

.EventName Standards
For the eventName, the standard will be the following fields separated by a colon (':') in camel case.

* PlatformProcess
* Action

.Tag Definition

* Format
** Ordered sets of tuples separated by underscore '_'

.Action Definition
The action defines the type of action or state changes of the process.

.Action Component Valid Values

Process Action Sample Values:

* Started
* Completed
* StateChanged

.Body Definition Considerations

* The eventData section is named 'eventData' 
** 'eventData' can be any valid JSON schema
* Contains one predefined element 'extension'
** Extension is a private area that can contain its schema
** The field is a map/array with:
*** Namespace as a key and,
*** Any valid JSON schema as its value
 This can be any significant data or data of interest for reporting at the time of the process state change.
